### ISSUE TITLE
nalgebra version bump to 0.16

### ISSUE THREAD

**Issue by ChristopherRabotin** [novacrazy/dual_num#10]
This isn't a big change at all (cf. [release notes](https://www.nalgebra.org/changelog/#version-016)), so let's keep in sync. I don't even know if this release does any speed improvements.

(Notice of conflict of interest: bumping this to version `0.16` will allow the library in which I use dual_num to also be upgraded to `0.16`.)

**Comment by novacrazy** [comment]
Hmm, I think you referenced the wrong issue in #11. I'll just close this now.
